[tool.poetry]
name = "chatapp-lld"
version = "0.1.0"
description = ""
authors = ["Shrine Sabu <39656631+shrine2000@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
